# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
This module is the get_public_key API handler.
It retrieves the public key generated by a custom resource stored in Secrets Manager.
"""

import boto3
import os
import redis
from botocore import config
from time import time
from boto3.dynamodb.conditions import Key, Attr
from counters import SERVING_COUNTER

SECRET_NAME_PREFIX = os.environ["STACK_NAME"]
SOLUTION_ID = os.environ['SOLUTION_ID']
EVENT_ID = os.environ["EVENT_ID"]
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
DDB_SVC_EXP_TABLE_NAME = os.environ['COUNTER_ISSUED_AT_TABLE']
QUEUE_POSITION_EXPIRY_PERIOD = os.environ['QUEUE_POSITION_EXPIRY_PERIOD']

user_agent_extra = {"user_agent_extra": SOLUTION_ID}
user_config = config.Config(**user_agent_extra)
boto_session = boto3.session.Session()
region = boto_session.region_name
ddb_resource = boto3.resource('dynamodb', endpoint_url=f'https://dynamodb.{region}.amazonaws.com', config=user_config)
ddb_svc_exp_table =  ddb_table = ddb_resource.Table(DDB_SVC_EXP_TABLE_NAME)
secrets_client = boto3.client('secretsmanager', config=user_config, endpoint_url=f'https://secretsmanager.{region}.amazonaws.com')
response = secrets_client.get_secret_value(SecretId=f"{SECRET_NAME_PREFIX}/redis-auth")
redis_auth = response.get("SecretString")
rc = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, ssl=True, decode_responses=True, password=redis_auth)

def lambda_handler(event, context):
    """
    This function is the entry handler for Lambda.
    """

    print(event)
    expiry_time = int(time()) + int(QUEUE_POSITION_EXPIRY_PERIOD)
    kce = Key('event_id').eq(EVENT_ID) & Key('issue_time').lte(expiry_time)
    response = ddb_table.query(
        KeyConditionExpression=kce,
        ScanIndexForward=True,
        FilterExpression=Attr('marked_obsolete').eq(0)
    )

    increment_by = 0
    for item in response['Items']:
        try:
            ddb_table.update_item(
                Key={
                    'event_id': item['event_id'],
                    'serving_position': item['serving_position']
                },
                UpdateExpression='SET obsolete = :val1',
                ExpressionAttributeValues={':val1': 1}
            )
            increment_by += (item['serving_position'] - item['served_positions_count'])
        except Exception as ex:
            print(ex)

    # increment the serving counter and update the table
    cur_serving = rc.incrby(SERVING_COUNTER, increment_by)

    item = {
        'event_id': EVENT_ID,
        'serving_position': cur_serving,
        'issue_time': int(time()),
        'obsolete': 0,
        'served_positions_count': 0
    }
    ddb_table.put_item(Item=item)
    
    print(f"cur_serving: {cur_serving}")
    print(item)