# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
This module is the get_public_key API handler.
It retrieves the public key generated by a custom resource stored in Secrets Manager.
"""

import boto3
import os
import redis
from botocore import config
from time import time
from boto3.dynamodb.conditions import Key, Attr
from counters import PREVIOUS_TABLE_SERVING_POSITION, SERVING_COUNTER

SECRET_NAME_PREFIX = os.environ["STACK_NAME"]
SOLUTION_ID = os.environ['SOLUTION_ID']
EVENT_ID = os.environ["EVENT_ID"]
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
DDB_SVC_EXP_TABLE_NAME = os.environ['COUNTER_ISSUED_AT_TABLE']
QUEUE_POSITION_EXPIRY_PERIOD = os.environ['QUEUE_POSITION_EXPIRY_PERIOD']

user_agent_extra = {"user_agent_extra": SOLUTION_ID}
user_config = config.Config(**user_agent_extra)
boto_session = boto3.session.Session()
region = boto_session.region_name
ddb_resource = boto3.resource('dynamodb', endpoint_url=f'https://dynamodb.{region}.amazonaws.com', config=user_config)
ddb_table = ddb_resource.Table(DDB_SVC_EXP_TABLE_NAME)
secrets_client = boto3.client('secretsmanager', config=user_config, endpoint_url=f'https://secretsmanager.{region}.amazonaws.com')
response = secrets_client.get_secret_value(SecretId=f"{SECRET_NAME_PREFIX}/redis-auth")
redis_auth = response.get("SecretString")
rc = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, ssl=True, decode_responses=True, password=redis_auth)

def lambda_handler(event, context):
    """
    This function is the entry handler for Lambda.
    """
    # scan for all items that are not obsolete 
    print(event)
    
    previous_serving_position = int(rc.get(PREVIOUS_TABLE_SERVING_POSITION))

    kce = Key('event_id').eq(EVENT_ID) & Key('serving_position').gte(previous_serving_position)
    fexp = Attr('obsolete').eq(0)
    response = ddb_table.query(
        KeyConditionExpression=kce,
        ScanIndexForward=False,
        FilterExpression=fexp
    )
    items = response['Items']

    # mark obsolete items with expired issue time
    obsolete_items = []
    current_time = int(time())
    for item in items:
        if current_time > item['issue_time'] + int(QUEUE_POSITION_EXPIRY_PERIOD):
            obsolete_items.append(item)
            ddb_table.update_item(
                    Key={
                        'event_id': item['event_id'],
                        'serving_position': item['serving_position']
                    },
                    UpdateExpression='SET obsolete = :val1',
                    ExpressionAttributeValues={':val1': 1}
                )

    # Calculate how much to increment the serving counter 
    # Difference in serving postions sum(Higher - Lower) - sum(served_positions_count)
    increment_by = 0
    items_count = len(obsolete_items)

    if items_count == 1:
        increment_by = obsolete_items[0]['serving_position'] - previous_serving_position
    elif items_count > 1:
        j = 0
        while j + 1 < items_count:
            increment_by += (obsolete_items[j + 1]['serving_position'] - obsolete_items[j]['serving_position'])
            j += 1
        increment_by -= previous_serving_position

    increment_by -= sum(item['served_positions_count'] for item in obsolete_items)

    print(f'Non-obsolete items found in scan: {len(items)}')
    print(f'Oboleted items: {items_count}')
    print(f'Increment by: {increment_by}')

    if obsolete_items:
        previous_serving_position = int(obsolete_items[-1]['serving_position'])
        rc.set(PREVIOUS_TABLE_SERVING_POSITION, previous_serving_position)
        print(f'Previous table serving position: {previous_serving_position}')

    if increment_by > 0:
        # increment the serving counter and update the table
        cur_serving = rc.incrby(SERVING_COUNTER, int(increment_by))

        item = {
            'event_id': EVENT_ID,
            'serving_position': cur_serving,
            'issue_time': int(time()),
            'obsolete': 0,
            'served_positions_count': 0
        }
        ddb_table.put_item(Item=item)
        print(item)
    
    print(f"cur_serving updated to: {rc.get(SERVING_COUNTER)}")